In [1]:
import pandas as pd
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split

### Scenario - 1

when target column has numercal continuous values

In [2]:
data = {
    "Education": [
        "High School", "Bachelor", "Master", "PhD",
        "Bachelor", "Master", "High School", "PhD",
        "Master", "Bachelor"
    ],

    "Experience": [
        "Fresher", "Junior", "Mid", "Senior",
        "Lead", "Mid", "Junior", "Lead",
        "Senior", "Fresher"
    ],

    "Salary": [
        20000, 25000, 40000, 50000, 45000, 40000, 25000, 35000, 50000, 20000
    ]
}

In [3]:
df = pd.DataFrame(data)
df

     Education Experience  Salary
0  High School    Fresher   20000
1     Bachelor     Junior   25000
2       Master        Mid   40000
3          PhD     Senior   50000
4     Bachelor       Lead   45000
5       Master        Mid   40000
6  High School     Junior   25000
7          PhD       Lead   35000
8       Master     Senior   50000
9     Bachelor    Fresher   20000

In [4]:
x = df.drop(columns='Salary')
y = df['Salary']

In [5]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size=0.8, random_state=42)

In [6]:
encoder = TargetEncoder()

encoder.fit_transform(xtrain, ytrain)

      Education    Experience
5  35172.912240  35172.912240
0  32690.518604  32335.890942
7  35527.539902  35172.912240
2  35172.912240  35172.912240
9  34109.029253  32335.890942
4  34109.029253  35172.912240
3  35527.539902  36407.944912
6  32690.518604  33155.233053

### Scenario - 2

when target column has categorical values

In [7]:
data = {
    "Education": [
        "High School", "Bachelor", "Master", "PhD",
        "Bachelor", "Master", "High School", "PhD",
        "Master", "Bachelor"
    ],

    "Experience": [
        "Fresher", "Junior", "Mid", "Senior",
        "Lead", "Mid", "Junior", "Lead",
        "Senior", "Fresher"
    ],

    "Performance": [
        "Poor", "Average", "Good", "Excellent",
        "Excellent", "Good", "Average", "Poor",
        "Good", "Excellent"
    ],

    "Salary": [
        "Low", "Medium", "High", "Very High",
        "Very High", "High", "Medium", "Low",
        "High", "Medium"
    ]
}

In [8]:
df1 = pd.DataFrame(data)
df1

     Education Experience Performance     Salary
0  High School    Fresher        Poor        Low
1     Bachelor     Junior     Average     Medium
2       Master        Mid        Good       High
3          PhD     Senior   Excellent  Very High
4     Bachelor       Lead   Excellent  Very High
5       Master        Mid        Good       High
6  High School     Junior     Average     Medium
7          PhD       Lead        Poor        Low
8       Master     Senior        Good       High
9     Bachelor    Fresher   Excellent     Medium

In [9]:
x = df1.drop(columns='Salary')
y = df1['Salary']

In [10]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size=0.8, random_state=42)

In [11]:
encoder = TargetEncoder()

encoder.fit_transform(xtrain, ytrain)

   Education  Experience  Performance
5   1.287223    1.287223     1.287223
0   1.500000    1.500000     1.429074
7   1.570926    1.570926     1.429074
2   1.287223    1.287223     1.287223
9   1.641851    1.500000     1.680209
4   1.641851    1.570926     1.680209
3   1.570926    1.695163     1.680209
6   1.500000    1.565054     1.565054

In [12]:
encoder.transform(xtest, ytest)

   Education  Experience  Performance
8   1.287223    1.695163     1.287223
1   1.641851    1.565054     1.565054

In [13]:
encoder.transform(xtest)

   Education  Experience  Performance
8   1.287223    1.695163     1.287223
1   1.641851    1.565054     1.565054

In [ ]:
encoder = TargetEncoder(cols=['Education'])

encoder.fit_transform(xtrain, ytrain)

   Education Experience Performance
5   1.287223        Mid        Good
0   1.500000    Fresher        Poor
7   1.570926       Lead        Poor
2   1.287223        Mid        Good
9   1.641851    Fresher   Excellent
4   1.641851       Lead   Excellent
3   1.570926     Senior   Excellent
6   1.500000     Junior     Average